### ISSUE TITLE
Running watch with IIS Express

### ISSUE THREAD

**Issue by zigzag95** [aspnet/dotnet-watch#143]
Any idea how to use dotnet-watch with IIS Express.
I'm using Windows authentication and this is not compliant with Kestrel

**Comment by victorhurdugaci** [comment]
Unfortunately, that's not supported.

`dotnet watch` is not ASP.NET specific, therefore it has no knowledge about IIS Express or any other web technology. It simply launches `dotnet` with some arguments. To start IIS Express you'd need a `dotnet` command that does the appropriate setup and that should be called instead of `dotnet-run`

**Comment by victorhurdugaci** [comment]
Closing the issue because launching IIS should be done by a different tool, not the watcher itself... Maybe this should go in IISIntegration or something. What do you think @Tratcher @moozzyk ?

**Comment by Tratcher** [comment]
Sounds like a VS tooling scenario. Or you could use WebListener instead.
