### ISSUE TITLE
`dnx-watch` hangs/is not notified about file changes on CoreClr on Mac OS

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dotnet-watch#21]
It will run the target project once but changes to file aren't ever detected.

Note that this works fine on Linux.

**Comment by victorhurdugaci** [comment]
Is this a known issue with the file watcher on CoreCLR/Darwin?

**Comment by muratg** [comment]
@victorhurdugaci let's investigate on our end. if there's a behavior difference between linux/windows and os x, we should file bugs on appropriate repo

**Comment by glennc** [comment]
When running inside a docker container and detecting changes on a mounted volume I needed to have Mono use the managed file watcher otherwise it wouldn't detect changes.

**Comment by davidfowl** [comment]
This is talking about CoreCLR not mono.

**Comment by glennc** [comment]
Didn't read the title.

**Comment by mikehaas763** [comment]
I'm having the same problem. Using CoreCLR and dnx beta 8. When I run `dnx-watch web` in my default yeoman scaffolded web project it will run the server and start the process and I can successfully visit the website in my browser. When I make a change to a view it reflects it as I would expect because they're being compiled on the fly anyway (I'm assuming). However, when I make a simple change to the HomeController I see no logging output in my terminal and when I refresh I don't see the change in my browser. The process **does** remain running though.

**Comment by muratg** [comment]
@victorhurdugaci Could you ping someone from CoreCLR to look into it?

cc @joshfree

**Comment by muratg** [comment]
@victorhurdugaci Does this work now?
